### ISSUE TITLE
Output rigid body information directly in matrix transforms

### ISSUE THREAD

**Issue by RenaudGervais** [RenaudGervais/vvvv.optitrack#1]
Right now, the rigid body information are output in a separate manner (position, euler and quaternion). It would be simpler to package all these in a matrix transform and let the end user use a `Decompose` node to retrieve individual information as needed. Ideally, we would put an enum input pin to choose in which coordinate system the matrix transform will be expressed (vvvv or OptiTrack).

**Comment by joansolroo** [comment]
Solved
